version: '3'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_php
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        depends_on:
            - php
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge
